Repository BeeKeeprs/was, pull requests merged in 2025-05, with the labels that each got.

#13 feat: 전역 응답 처리 설정 추가
  src/main/java/kr/co/webee/common/error/ErrorType.java
  src/main/java/kr/co/webee/common/error/exception/BaseException.java
  src/main/java/kr/co/webee/common/error/exception/BusinessException.java
  src/main/java/kr/co/webee/common/error/exception/NotFoundException.java
  src/main/java/kr/co/webee/presentation/handler/ApiResponseHandler.java
  src/main/java/kr/co/webee/presentation/handler/ExceptionRestHandler.java
  src/main/java/kr/co/webee/presentation/response/ApiErrorDto.java
  src/main/java/kr/co/webee/presentation/response/ApiResponse.java
Labels: ⚙️ Setting

#15 feat: Swagger 설정 추가
  build.gradle
  src/main/java/kr/co/webee/presentation/annotation/ApiDocsErrorType.java
  src/main/java/kr/co/webee/presentation/config/SwaggerConfig.java
Labels: 📑 Documentation

#24 chore: cors 설정
  src/main/java/kr/co/webee/infrastructure/config/CorsConfig.java
  src/main/java/kr/co/webee/infrastructure/config/SecurityConfig.java
Labels: ⚙️ Setting

#25 fix: redis password가 있다면 사용하도록 수정
  src/main/java/kr/co/webee/infrastructure/config/RedisConfig.java
  src/main/resources/.env.example
  src/main/resources/application.yml
Labels: 🔨 Fix

#28 fix: redis ssl 설정 기능 추가
  build.gradle
  src/main/java/kr/co/webee/infrastructure/config/RedisConfig.java
  src/main/resources/.env.example
  src/main/resources/application.yml
Labels: 🐞 Bug

#34 feat: 상품 리뷰 API 추가
  src/main/java/kr/co/webee/application/product/service/ProductReviewService.java
  src/main/java/kr/co/webee/domain/product/entity/ProductReview.java
  src/main/java/kr/co/webee/domain/product/repository/ProductReviewRepository.java
  src/main/java/kr/co/webee/presentation/handler/ExceptionRestHandler.java
  src/main/java/kr/co/webee/presentation/product/api/ProductApi.java
  src/main/java/kr/co/webee/presentation/product/api/ProductReviewApi.java
  src/main/java/kr/co/webee/presentation/product/api/ProductUploadForm.java
  src/main/java/kr/co/webee/presentation/product/controller/ProductController.java
  src/main/java/kr/co/webee/presentation/product/controller/ProductReviewController.java
  src/main/java/kr/co/webee/presentation/product/dto/request/ProductReviewCreateRequest.java
  src/main/java/kr/co/webee/presentation/product/dto/request/ProductReviewUpdateRequest.java
  src/main/java/kr/co/webee/presentation/product/dto/response/ProductReviewResponse.java
Labels: ✨ Feature

#35 fix: Swagger CORS 에러 수정
  src/main/java/kr/co/webee/infrastructure/config/CorsConfig.java
  src/main/java/kr/co/webee/infrastructure/config/SecurityConfig.java
  src/main/java/kr/co/webee/presentation/config/SwaggerConfig.java
  src/main/resources/.env.example
  src/main/resources/application.yml
Labels: 🐞 Bug

#36 fix: security cors 설정 오타 수정
  src/main/java/kr/co/webee/infrastructure/config/SecurityConfig.java
Labels: 🐞 Bug

#37 fix: 로그인 응답값에 사용자 이름 추가
  src/main/java/kr/co/webee/application/auth/dto/SignInResponse.java
  src/main/java/kr/co/webee/application/auth/service/AuthService.java
  src/main/java/kr/co/webee/presentation/auth/api/AuthApi.java
  src/main/java/kr/co/webee/presentation/auth/controller/AuthController.java
  src/test/java/kr/co/webee/application/auth/service/AuthServiceTest.java
Labels: 🔨 Fix

#40 fix: product 테이블 name 컬럼 추가
  src/main/java/kr/co/webee/application/product/service/ProductSaverService.java
  src/main/java/kr/co/webee/application/product/service/ProductService.java
  src/main/java/kr/co/webee/domain/product/entity/Product.java
  src/main/java/kr/co/webee/presentation/product/dto/request/ProductCreateRequest.java
  src/main/java/kr/co/webee/presentation/product/dto/request/ProductUpdateRequest.java
  src/main/java/kr/co/webee/presentation/product/dto/response/ProductResponse.java
Labels: 🔨 Fix

#43 feat: aws s3 의존성 연결 client 클래스 추가
  build.gradle
  src/main/java/kr/co/webee/application/product/service/ProductService.java
  src/main/java/kr/co/webee/common/error/ErrorType.java
  src/main/java/kr/co/webee/infrastructure/storage/FileStorageClient.java
  src/main/java/kr/co/webee/infrastructure/storage/MockFileStorage.java
  src/main/java/kr/co/webee/infrastructure/storage/s3/AwsS3Config.java
  src/main/java/kr/co/webee/infrastructure/storage/s3/S3FileStorageClient.java
  src/main/resources/.env.example
  src/main/resources/application.yml
  src/test/java/kr/co/webee/annotation/IntegrationTest.java
  src/test/java/kr/co/webee/config/AwsS3TestConfig.java
Labels: ✨ Feature

#47 feat: Product 전체 조회 API 추가
  src/main/java/kr/co/webee/application/product/service/ProductService.java
  src/main/java/kr/co/webee/presentation/config/SwaggerConfig.java
  src/main/java/kr/co/webee/presentation/config/WebConfig.java
  src/main/java/kr/co/webee/presentation/product/api/ProductApi.java
  src/main/java/kr/co/webee/presentation/product/controller/ProductController.java
Labels: ✨ Feature

#46 feat: Spring AI 설정
  build.gradle
  src/main/java/kr/co/webee/application/document/VectorDocumentService.java
  src/main/java/kr/co/webee/infrastructure/config/ai/AiConfig.java
  src/main/java/kr/co/webee/presentation/document/api/VectorDocumentApi.java
  src/main/java/kr/co/webee/presentation/document/controller/VectorDocumentController.java
  src/main/java/kr/co/webee/presentation/document/dto/VectorDocumentRequest.java
  src/main/java/kr/co/webee/presentation/document/dto/VectorDocumentResponse.java
  src/main/resources/.env.example
  src/main/resources/application.yml
  src/test/java/kr/co/webee/annotation/IntegrationTest.java
  src/test/java/kr/co/webee/config/TestAiConfig.java
Labels: ✨ Feature

#48 feat: 사용자 질의응답 API 추가
  src/main/java/kr/co/webee/application/ai/AssistantService.java
  src/main/java/kr/co/webee/application/ai/RagSearchOptions.java
  src/main/java/kr/co/webee/infrastructure/config/SecurityConfig.java
  src/main/java/kr/co/webee/infrastructure/config/ai/AssistantAiExecutor.java
  src/main/java/kr/co/webee/presentation/ai/chat/api/AssistantApi.java
  src/main/java/kr/co/webee/presentation/ai/chat/controller/AssistantController.java
  src/main/java/kr/co/webee/presentation/ai/chat/dto/AssistantRequest.java
  src/main/java/kr/co/webee/presentation/ai/chat/dto/AssistantResponse.java
  src/main/resources/application.yml
Labels: ✨ Feature

#49 fix: 프롬프트를 txt 파일에 저장하도록 변경
  src/main/java/kr/co/webee/application/ai/AssistantService.java
  src/main/resources/application.yml
  src/main/resources/prompts/direct_answer_strict.txt
Labels: 🔨 Fix

#59 fix: openai 모델을 4o에서 4o-mini로 변경
  src/main/resources/application.yml
Labels: 🔨 Fix
